locationFile: './data/LocationsOct11.csv'
edgeFile: './data/EdgesOct11.csv'
prefFile: './data/demoPref.csv'
startLoc: 'AtlantaGA'
resultFile: './output/RoundTripDemo1.csv'
maxTime: 20
x_mph: 60


attractionFile: "./data/attractions.tsv"
themeFile: "./data/themes.tsv"
maxSamples: 20


hidden_layers: [4, 4]
num_folds: 5
num_trials: 5
epochs: 200
lr: 0.05